apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dedicated-admins-openshift-codeready-workspaces
  namespace: openshift-codeready-workspaces
  labels:
    api.openshift.com/managed: "true"
subjects:
- kind: Group
  name: dedicated-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dedicated-admins-openshift-codeready-workspaces
