apiVersion: v1
kind: Namespace
metadata:
  name: openshift-velero
  labels:
    openshift.io/cluster-monitoring: "true"
    api.openshift.com/managed: "true"
    hive.openshift.io/cluster-platform: "aws"
