apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cluster-config-v1-reader
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - cluster-config-v1
  resources:
  - configmaps
  verbs:
  - get
