kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-velero-operator
  namespace: openshift-velero
  labels:
    hive.openshift.io/cluster-platform: "aws"
subjects:
- kind: ServiceAccount
  name: managed-velero-operator
  namespace: openshift-velero
roleRef:
  kind: Role
  name: managed-velero-operator
  apiGroup: rbac.authorization.k8s.io
