kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: managed-velero-operator-cluster-config-v1-reader
  namespace: kube-system
  labels:
    owner: managed-velero-operator
    owner.namespace: managed-velero-operator
    api.openshift.com/managed: "true"
    hive.openshift.io/cluster-platform: "aws"
subjects:
- kind: ServiceAccount
  name: managed-velero-operator
  namespace: openshift-velero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-config-v1-reader
