kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s
  namespace: openshift-velero
  labels:
    hive.openshift.io/cluster-platform: "aws"
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
