kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: velero
  labels:
    api.openshift.com/managed: "true"
    hive.openshift.io/cluster-platform: "aws"
subjects:
- kind: ServiceAccount
  name: velero
  namespace: openshift-velero
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
