apiVersion: apps/v1
kind: Deployment
metadata:
  name: managed-velero-operator
  namespace: openshift-velero
  labels:
    api.openshift.com/managed: "true"
    hive.openshift.io/cluster-platform: "aws"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: managed-velero-operator
  template:
    metadata:
      labels:
        name: managed-velero-operator
    spec:
      serviceAccountName: managed-velero-operator
      containers:
        - name: managed-velero-operator
          image: quay.io/openshift-sre/managed-velero-operator:v0.1.35-49347f0
          command:
          - managed-velero-operator
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "managed-velero-operator"
