apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-alerts-stuck-volumes
    role: alert-rules
    api.openshift.com/managed: "true"
    hive.openshift.io/cluster-platform: "aws"
  name: sre-alerts-stuck-volumes
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-alerts-stuck-volumes
    rules:
    - alert: EbsVolumeStuckAttaching5MinSRE
      expr: min_over_time(ebs_volume_state{ebs_volume_state="attaching"}[5m]) == 1
      labels:
        severity: warning
        namespace: openshift-monitoring
    - alert: EbsVolumeStuckAttaching10MinSRE
      expr: min_over_time(ebs_volume_state{ebs_volume_state="attaching"}[10m]) == 1
      labels:
        severity: critical
        namespace: openshift-monitoring
    - alert: EbsVolumeStuckDetaching5MinSRE
      expr: min_over_time(ebs_volume_state{ebs_volume_state="detaching"}[5m]) == 1
      labels:
        severity: warning
        namespace: openshift-monitoring
    - alert: EbsVolumeStuckDetaching10MinSRE
      expr: min_over_time(ebs_volume_state{ebs_volume_state="detaching"}[10m]) == 1
      labels:
        severity: critical
        namespace: openshift-monitoring